### ISSUE TITLE
buzztrax-0.10.2 fails to build with fluidsynth-1.1.9

### ISSUE THREAD

**Issue by plater** [Buzztrax/buzztrax#74]
Buzztrax released version uses at least two functions that are depreciated in fluidsynth-1.1.9.
I've added "-Wno-error=deprecated-declarations" to the list of flags in it's build as a work around.

src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_get_property':
src/gst/fluidsynth/fluidsynth.c:585:9: error: 'fluid_settings_getstr' is deprecated (declared at /usr/include/fluidsynth/settings.h:152) [-Werror=deprecated-declarations]
         retval = fluid_settings_getstr (src->settings, name, &s);
         ^
src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_init':
src/gst/fluidsynth/fluidsynth.c:719:5: error: 'fluid_synth_set_midi_router' is deprecated (declared at /usr/include/fluidsynth/synth.h:321) [-Werror=deprecated-declarations]
     fluid_synth_set_midi_router (src->fluid, src->midi_router);
     ^

**Comment by plater** [comment]
Due to a gcc7 update I've now had to add -Wno-error=incompatible-pointer-types to the build as well.
Extra flags needed for gcc7 build so far are:
-Wno-error=format-truncation= -Wno-error=format-overflow= -Wno-error=incompatible-pointer-types
Gcc8 has been released.

**Comment by plater** [comment]
@ensonic  Buzztrax 0.10.2 is getting very tatty, it no longer builds with fluidsynth-2.0.0
I'm switching to git

**Comment by ensonic** [comment]
Thanks for the reports. I'll see if I can set some time aside to make a maintenance release with such fixes.

**Comment by ensonic** [comment]
This is fixed with these two commits:
a3e7447885137a7569da948b5fb847829dfdb835
b39563b237f82408bc4929d38d52d6ebd4a513b7

**Comment by plater** [comment]
Still have a problem with src/gst/fluidsynth/fluidsynth.c:
src/gst/fluidsynth/fluidsynth.c: In function 'settings_foreach_func':
src/gst/fluidsynth/fluidsynth.c:234:14: error: too few arguments to function 'fluid_settings_getnum_default'
       ddef = fluid_settings_getnum_default (bag->settings, name);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:135:5: note: declared here
 int fluid_settings_getnum_default(fluid_settings_t *settings, const char *name, double *val);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:240:14: error: too few arguments to function 'fluid_settings_getint_default'
       idef = fluid_settings_getint_default (bag->settings, name);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:148:5: note: declared here
 int fluid_settings_getint_default(fluid_settings_t *settings, const char *name, int *val);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:245:16: error: too few arguments to function 'fluid_settings_getstr_default'
       defstr = fluid_settings_getstr_default (bag->settings, name);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:123:5: note: declared here
 int fluid_settings_getstr_default(fluid_settings_t *settings, const char *name, char **def);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_init':
src/gst/fluidsynth/fluidsynth.c:727:24: error: too few arguments to function 'new_fluid_cmd_handler'
     src->cmd_handler = new_fluid_cmd_handler (src->fluid);
                        ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:98:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/shell.h:49:22: note: declared here
 fluid_cmd_handler_t *new_fluid_cmd_handler(fluid_synth_t *synth, fluid_midi_router_t *router);
                      ^~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_class_init':
src/gst/fluidsynth/fluidsynth.c:781:40: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_set_log_function (FLUID_PANIC, gstbt_fluid_synth_error_log_function,
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void (*)(int,  const char *, void *)}' but argument is of type 'void (*)(int,  char *, void *)'
 fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void *data);
                      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:783:38: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_set_log_function (FLUID_ERR, gstbt_fluid_synth_warning_log_function,
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void (*)(int,  const char *, void *)}' but argument is of type 'void (*)(int,  char *, void *)'
 fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void *data);
                      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:785:39: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_set_log_function (FLUID_WARN, gstbt_fluid_synth_warning_log_function,
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void (*)(int,  const char *, void *)}' but argument is of type 'void (*)(int,  char *, void *)'
 fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void *data);
                      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:787:39: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_set_log_function (FLUID_INFO, gstbt_fluid_synth_info_log_function,
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void (*)(int,  const char *, void *)}' but argument is of type 'void (*)(int,  char *, void *)'
 fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void *data);
                      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:789:38: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_set_log_function (FLUID_DBG, gstbt_fluid_synth_debug_log_function,
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void (*)(int,  const char *, void *)}' but argument is of type 'void (*)(int,  char *, void *)'
 fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void *data);
                      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:803:49: warning: passing argument 3 of 'fluid_settings_foreach' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_settings_foreach (bag.settings, &count, settings_foreach_count);
                                                 ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:181:6: note: expected 'fluid_settings_foreach_t {aka void (*)(void *, const char *, int)}' but argument is of type 'void (*)(void *, char *, int)'
 void fluid_settings_foreach(fluid_settings_t *settings, void *data,
      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:812:47: warning: passing argument 3 of 'fluid_settings_foreach' from incompatible pointer type [-Wincompatible-pointer-types]
   fluid_settings_foreach (bag.settings, &bag, settings_foreach_func);
                                               ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
                 from src/gst/fluidsynth/fluidsynth.h:30,
                 from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:181:6: note: expected 'fluid_settings_foreach_t {aka void (*)(void *, const char *, int)}' but argument is of type 'void (*)(void *, char *, int)'
 void fluid_settings_foreach(fluid_settings_t *settings, void *data,
      ^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:889:11: error: 'FLUID_CHORUS_DEFAULT_TYPE' undeclared (first use in this function); did you mean 'FLUID_VOICE_DEFAULT'?
           FLUID_CHORUS_DEFAULT_TYPE,
           ^~~~~~~~~~~~~~~~~~~~~~~~~
           FLUID_VOICE_DEFAULT
src/gst/fluidsynth/fluidsynth.c:889:11: note: each undeclared identifier is reported only once for each function it appears in

**Comment by plater** [comment]
Sorry fluidsynth 2 has been current for such a long time I didn't realise this issue was for an earlier version.
