### ISSUE TITLE
Buzztrax fails to build with fluidsynth >= 2.0.0

### ISSUE THREAD

**Issue by plater** [Buzztrax/buzztrax#87]
See http://www.fluidsynth.org/api/settings_8h.html
Still have a problem with src/gst/fluidsynth/fluidsynth.c:
src/gst/fluidsynth/fluidsynth.c: In function 'settings_foreach_func':
src/gst/fluidsynth/fluidsynth.c:234:14: error: too few arguments to function 'fluid_settings_getnum_default'
ddef = fluid_settings_getnum_default (bag->settings, name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:135:5: note: declared here
int fluid_settings_getnum_default(fluid_settings_t *settings, const char *name, double *val);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:240:14: error: too few arguments to function 'fluid_settings_getint_default'
idef = fluid_settings_getint_default (bag->settings, name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:148:5: note: declared here
int fluid_settings_getint_default(fluid_settings_t *settings, const char *name, int *val);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:245:16: error: too few arguments to function 'fluid_settings_getstr_default'
defstr = fluid_settings_getstr_default (bag->settings, name);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:123:5: note: declared here
int fluid_settings_getstr_default(fluid_settings_t *settings, const char *name, char **def);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_init':
src/gst/fluidsynth/fluidsynth.c:727:24: error: too few arguments to function 'new_fluid_cmd_handler'
src->cmd_handler = new_fluid_cmd_handler (src->fluid);
^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:98:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/shell.h:49:22: note: declared here
fluid_cmd_handler_t *new_fluid_cmd_handler(fluid_synth_t *synth, fluid_midi_router_t router);
^~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c: In function 'gstbt_fluid_synth_class_init':
src/gst/fluidsynth/fluidsynth.c:781:40: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_set_log_function (FLUID_PANIC, gstbt_fluid_synth_error_log_function,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void ()(int, const char *, void )}' but argument is of type 'void ()(int, char *, void *)'
fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void data);
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:783:38: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_set_log_function (FLUID_ERR, gstbt_fluid_synth_warning_log_function,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void ()(int, const char *, void )}' but argument is of type 'void ()(int, char *, void *)'
fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void data);
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:785:39: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_set_log_function (FLUID_WARN, gstbt_fluid_synth_warning_log_function,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void ()(int, const char *, void )}' but argument is of type 'void ()(int, char *, void *)'
fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void data);
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:787:39: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_set_log_function (FLUID_INFO, gstbt_fluid_synth_info_log_function,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void ()(int, const char *, void )}' but argument is of type 'void ()(int, char *, void *)'
fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void data);
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:789:38: warning: passing argument 2 of 'fluid_set_log_function' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_set_log_function (FLUID_DBG, gstbt_fluid_synth_debug_log_function,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:105:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/log.h:76:22: note: expected 'fluid_log_function_t {aka void ()(int, const char *, void )}' but argument is of type 'void ()(int, char *, void *)'
fluid_log_function_t fluid_set_log_function(int level, fluid_log_function_t fun, void data);
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:803:49: warning: passing argument 3 of 'fluid_settings_foreach' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_settings_foreach (bag.settings, &count, settings_foreach_count);
^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:181:6: note: expected 'fluid_settings_foreach_t {aka void ()(void *, const char , int)}' but argument is of type 'void ()(void *, char *, int)'
void fluid_settings_foreach(fluid_settings_t *settings, void data,
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:812:47: warning: passing argument 3 of 'fluid_settings_foreach' from incompatible pointer type [-Wincompatible-pointer-types]
fluid_settings_foreach (bag.settings, &bag, settings_foreach_func);
^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:96:0,
from src/gst/fluidsynth/fluidsynth.h:30,
from src/gst/fluidsynth/fluidsynth.c:89:
/usr/include/fluidsynth/settings.h:181:6: note: expected 'fluid_settings_foreach_t {aka void ()(void *, const char , int)}' but argument is of type 'void ()(void *, char *, int)'
void fluid_settings_foreach(fluid_settings_t *settings, void *data,
^~~~~~~~~~~~~~~~~~~~~~
src/gst/fluidsynth/fluidsynth.c:889:11: error: 'FLUID_CHORUS_DEFAULT_TYPE' undeclared (first use in this function); did you mean 'FLUID_VOICE_DEFAULT'?
FLUID_CHORUS_DEFAULT_TYPE,
^~~~~~~~~~~~~~~~~~~~~~~~~
FLUID_VOICE_DEFAULT
src/gst/fluidsynth/fluidsynth.c:889:11: note: each undeclared identifier is reported only once for each function it appears in

**Comment by ensonic** [comment]
I have only 1.1.11 here. Are 1.X and 2.X installed in parallel? If so it is probably better to build against 1.X for now.

**Comment by plater** [comment]
Unfortunately Tumbleweed switched to Fluidsynth2 last year, I'll have to leave it disabled.

**Comment by plugwash** [comment]
This issue has now impacted Debian too, so I took a look and got the Debian package building.

The first thing I did was add -Werror=incompatible-pointer-types because I saw some worrying warnings in addition to the errors and did not want to miss them later, I also added -Werror=implicit-function-declaration later for similar reasons.

Unfortunately that caused build failures in other parts of the code, in particular conversions to/from GOBject * I fixed these by adding casts ( 0007-add-gobject-casts.patch)

Then it was on to the actual fixing of the fluidsynth stuff, with most of it, it was pretty obvious how to make the new code behave the same as the old code, but there were a couple of questionable cases.

The first is that FLUID_CHORUS_DEFAULT_TYPE had been removed, I replaced it with FLUID_CHORUS_MOD_SINE (which it had previously been #define'd to)

The second was that fluid_synth_set_midi_router has been removed, the documentation says "remove deprecated fluid_synth_set_midi_router(), instead supply the midi-router instance when creating a command handler with new_fluid_cmd_handler()", I replaced fluid_synth_set_midi_router with new_fluid_cmd_handler, but was not sure if that is sufficient or if more changes were required.

With these changes (and some minor packaging stuff which I won't mention here) the debian package built, I have not tested if it actually works.

I then attempted to apply my patches to the upstream source, 0007-add-gobject-casts.patch failed to apply, and on inspection it looks like similar changes have already been made upstream.

The actual fluidsynth patch was more interesting, two of the hunks failed to apply, and on inspection it seems both represented things that had already been altered, including the case where I had to make the most questionable change. YAY! I also decided to go ahead and add conditionals to my changes at this point, so that the same codebase could be used with both 1.x and 2.x.

Unfortunately I was not able to do a test build of the upstream buzztrax code due to an unrelated error*. So I then went and tried applying the upstream changes I had identified and my remaining changes back to the Debian version.

This revealed that there were still a slight issue with the midi router/command handler related code, so I fixed that too.

I have posted a pull request at https://github.com/Buzztrax/buzztrax/pull/90

\* Something seemed to go wrong in Makefile generation
```
make[2]: Entering directory '/buzztrax/docs/help/bt-edit'
Makefile:758: *** missing separator.  Stop.
```

**Comment by plater** [comment]
I tried 0001-Fix-build-with-fluidsynth-2.x.patch and I'm now able to include fluidsynth in the build. The patch messes up the build with fluidsynth1 though.

**Comment by plugwash** [comment]
Looks like I made a typo when adding the conditional logic to support both fluidsynth1 and fluidsynth2, I just updated the patch to fix that.

**Comment by plugwash** [comment]
Still showing a test failure in travis CI, but i don't think said failure has anything to do with my patch.

**Comment by plater** [comment]
@plugwash revised 0001-Fix-build-with-fluidsynth-2.x.patch now works with fluidsynth one and two

**Comment by ensonic** [comment]
Should be fixed with PR #90 . travis is broken and I spend way too much time trying to fix it :/
